server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/japnika
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
liquibase:
  enabled: true
  change-log: classpath:/liquibase/db-changelog.xml
logging:
  level: debug


