server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/japnika
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
liquibase:
  enabled: true
  change-log: classpath:/liquibase/db-changelog.xml
